# Generated by Django 4.2.16 on 2025-02-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_answer_options_alter_diagnostika_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
        migrations.AlterModelTable(
            name='diagnostika',
            table='diagnostika',
        ),
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
