# Generated by Django 4.2.16 on 2025-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnostikaSubjectAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'diagnostika_subject_association',
                'managed': False,
            },
        ),
    ]
